module.exports = Object.freeze({
    SELECT_ALL_QUOTES: "SELECT * FROM QUOTE",
    INSERT_QUOTE: "INSERT INTO QUOTE (QUOTE, AUTHOR) VALUES ('@quote', '@author')",
    SELECT_QUOTE_BY_ID: "SELECT * FROM QUOTE WHERE ID = '@id'",
    INSERT_USER: "INSERT INTO USER (EMAIL, PASSWORD, ROL, LAST_LOGIN_DATE) VALUES ('@email', '@password', '@rol', '@lastLoginDate')",
    SELECT_USER_PASSWORD: "SELECT ID, PASSWORD FROM USER WHERE EMAIL = '@email'",
    SELECT_USER_DATA: "SELECT ID, EMAIL, PASSWORD, ROL, CREATION_DATE, LAST_LOGIN_DATE FROM USER WHERE ID = '@id'",
    UPDATE_USER_LAST_LOGIN: "UPDATE USER SET LAST_LOGIN_DATE = '@lastLoginDate' WHERE ID = '@id'"
});